### ISSUE TITLE
Not a issue, more a discussion

### ISSUE THREAD

**Issue by ericqu** [st--/LinearRegression.jl#11]
Hi @st-- , 
Sorry to contact you this way; I could not find your email.
I had similar thoughts about Linear regression and did something similar (https://github.com/ericqu/LinearRegression.jl), although I chose a different route. While some features overlap, the objectives of our respective packages are different.
Only issue is that we chose the same name; I guess that was the most obvious choice for both of us.
Do you intend to keep your package name? If yes, no stress, I will search for another name (if you have any idea, please shoot). If not, please let me know.
Eric

**Comment by st--** [comment]
Hi @ericqu ! Thanks for getting in touch:) I would like to keep `LinearRegressions` for this minimal-dependencies, bare-bones quick linear regression. I had a quick look through your code: what's the key point you're trying to address that would be missing in GLM.jl, and that requires making it a new package? Knowing that more clearly might help with finding a good name for it! As noted in the README, there are already plenty of more advanced linear regression packages. So I'm wondering if your work might not find a much wider reach if it might be possible to turn it into an extension that you could contribute directly to GLM.jl, for example ?

**Comment by ericqu** [comment]
Thanks for getting back to me. 
Well, at the beginning I needed some extra statistics that GLM did not provide. I come from the SAS world and was kind of comfortable in using the PROC REG, PROC GLM, etc., and was expecting something similar in Julia. So I am trying to put together a package that gives as much as possible about the linear regression without the user having to look for the combination(s) of packages and code all the necessary things to bind them together (and the plots). Since I am looking for users that do not just want to find the coefficients, I am thinking that maybe I put an emphasis on the analysis part of the regression.
As a side note, as your package is aiming for speed/performance as well you could look into the sweep operator (you can see that part in the code) as for me it goes faster than GLM. 
In particular, I did not fully optimize the sweep operations because when they are executed out of order I lose the by-products of solving the linear system (the sum of squares errors) but in your case, if you don't need these statistics you might be able to optimize the algorithm further.
