### ISSUE TITLE
Add add usage to README

### ISSUE THREAD

**Issue by dpsanders** [st--/LinearRegression.jl#13]
The README says what this package does not do, but does not say what it *does* do! Or how to do it.

**Comment by st--** [comment]
Thank you, that's an excellent point @dpsanders ! I've added this in https://github.com/st--/LinearRegression.jl/pull/14/files : what do you think of that? Is that sufficient? What else might you want to see ?

**Comment by st--** [comment]
@dpsanders thanks for the prod to improve the README; if you've got any further thoughts, please don't hesitate to re-open this issue:) (I might miss it if you comment without reopening!)
